[[constraint]]
  branch = "master"
  name = "github.com/catalinc/hashcash"

[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.6.1"

[prune]
  go-tests = true
  unused-packages = true
